# -*- coding: utf-8 -*-
"""Stats_for_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6SMJnta1Mpf5QAhXE9_IeS0k1eDmr61
"""

pip install scikit_posthocs

import pandas as pd
import numpy as np
import scipy.stats as ss
import scikit_posthocs as sp
from scipy.stats import tukey_hsd
import matplotlib.pyplot as plt

# Import PyDrive and associated libraries.
# This only needs to be done once per notebook.
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
# This only needs to be done once per notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# Download a file based on its file ID.
#
# A file ID looks like: laggVyWshwcyP6kEI-y_W3P8D26sz

#https://drive.google.com/file/d/15bYglPgj7M249HOKG0bQ5mzxVtTCoK9K/view?usp=drive_link

## trade data upload
file = 'https://drive.google.com/file/d/15bYglPgj7M249HOKG0bQ5mzxVtTCoK9K/view?usp=drive_link'
id = '15bYglPgj7M249HOKG0bQ5mzxVtTCoK9K'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('trade_cv_result.csv')


'''
# Qty data upload
file = 'https://drive.google.com/file/d/1BvUzy2TiipALQlnw85-hCWbU6G0uv2oa/view?usp=drive_link'
id = '1BvUzy2TiipALQlnw85-hCWbU6G0uv2oa'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('trade_cv_result.csv')
'''

col_names = ['cv', 'LR', 'kNN', 'SVR', 'RF', 'Bagging', 'AdaBoost']

pd.set_option('display.max_columns', 200)
df = pd.read_csv('trade_cv_result.csv', delim_whitespace=True, header=None, skiprows=1)
df.head()

df.columns = col_names
df.head()

# drop first column
new_df = df.drop('cv', axis=1)
new_df.head()

# Convert dataframe to numpy array

df_array = new_df[['LR', 'kNN', 'SVR', 'RF', 'Bagging', 'AdaBoost']].to_numpy()

df_array

"""## Perform ANOVA test."""

ss.f_oneway(*df_array.T)

"""The ANOVA result above shows that we can reject the null hypothesis that the generalization performance of the developed are equal, because p value is less than 0.05. This means that the models do not perform similarly. Then, we can perform a posthoc test using Tukey test to verify the model that actually differ from the other, i.e pairwise comparison.


In Tukey test, we need to get the difference between mean rankings among all the models (comparing pairs of models). If this difference is greater than or equal to a CD (critic distance), we can say that these two classifiers are significantly different from each other.
"""

res = tukey_hsd(*df_array.T)
print(res)

"""# Critical Difference (CD) Plot"""

new_df.head()

cd_data = (
  pd.DataFrame(new_df)
  .rename_axis('cv_fold')
  .melt(
      var_name='estimator',
      value_name='score',
      ignore_index=False,
  )
  .reset_index()
)
cd_data

"""## The average (percentile) ranks could be calculated as follows:"""

avg_rank = cd_data.groupby('cv_fold').score.rank(pct=True).groupby(cd_data.estimator).mean()
avg_rank

#Collect the results of a post hoc Conover test

test_results = sp.posthoc_conover_friedman(
    cd_data,
    melted=True,
    block_col='cv_fold',
    group_col='estimator',
    y_col='score',
)
sp.sign_plot(test_results)

"""Again, based on the result above, the omnibus test result shows we can confidently reject the null hypothesis that all models come from the same distribution and proceed to the post hoc analysis."""

# Plot the critical difference plot
plt.figure(figsize=(10, 2), dpi=100)
plt.title('Critical difference diagram of average score ranks')
sp.critical_difference_diagram(avg_rank, test_results)